import io
import re
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from output.svg_renderer import svg_to_png_bytes


SECTION_COLORS = {
    "A": RGBColor(0x1D, 0x4E, 0xD8),
    "B": RGBColor(0xD9, 0x77, 0x06),
    "C": RGBColor(0x05, 0x96, 0x69),
    "D": RGBColor(0x7C, 0x3A, 0xED),
    "E": RGBColor(0xDB, 0x27, 0x77),
}


def generate_docx(
    content: str,
    subject: str,
    grade: str,
    board: str,
    total_marks: int,
    duration: str,
) -> bytes:
    doc = Document()

    for sec in doc.sections:
        sec.top_margin    = Inches(1)
        sec.bottom_margin = Inches(1)
        sec.left_margin   = Inches(1.25)
        sec.right_margin  = Inches(1.25)

    # ── Title block ───────────────────────────────────────────────────────────
    title = doc.add_heading(subject.upper(), level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if title.runs:
        title.runs[0].font.color.rgb = RGBColor(0x0F, 0x17, 0x2A)
        title.runs[0].font.size = Pt(18)

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta.add_run(f"Class: {grade}  ·  Board: {board}  ·  Max Marks: {total_marks}  ·  Duration: {duration}")
    run.font.size = Pt(11)
    run.bold = True
    run.font.color.rgb = RGBColor(0x33, 0x41, 0x55)

    # Horizontal rule via border paragraph
    border_para = doc.add_paragraph()
    border_para.paragraph_format.space_after = Pt(4)
    pPr = border_para._p.get_or_add_pPr()
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '6')
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), '334155')
    pBdr.append(bottom)
    pPr.append(pBdr)

    # ── Pre-process: extract SVG blocks ─────────────────────────────────────
    svg_map: dict[str, str] = {}
    def _extract(m):
        key = f"__SVG_{len(svg_map)}__"
        svg_map[key] = m.group(1).strip()
        return key
    content = re.sub(r'<SVG_DIAGRAM>\s*(.*?)\s*</SVG_DIAGRAM>', _extract, content, flags=re.DOTALL)

    # ── Body ─────────────────────────────────────────────────────────────────
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            sp = doc.add_paragraph()
            sp.paragraph_format.space_after = Pt(2)
            continue

        # SVG diagram → PNG image
        if stripped in svg_map:
            png = svg_to_png_bytes(svg_map[stripped], max_width=500)
            if png:
                doc.add_picture(io.BytesIO(png), width=Inches(5.5))
                last_para = doc.paragraphs[-1]
                last_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            else:
                p = doc.add_paragraph("[Diagram — see question paper for image]")
                p.runs[0].font.color.rgb = RGBColor(0x64, 0x74, 0x8B)
                p.runs[0].font.italic = True
            continue

        upper = stripped.upper()

        # Section heading
        if any(f"SECTION {c}" in upper for c in "ABCDE") or (stripped.startswith("---") and stripped.endswith("---")):
            ltr = next((c for c in "ABCDE" if f"SECTION {c}" in upper), "A")
            h = doc.add_heading(stripped.strip("-").strip(), level=2)
            h.paragraph_format.space_before = Pt(14)
            if h.runs:
                h.runs[0].font.color.rgb = SECTION_COLORS.get(ltr, RGBColor(0x1D, 0x4E, 0xD8))
                h.runs[0].font.size = Pt(13)

        # Answer key heading
        elif "ANSWER" in upper and ("KEY" in upper or "SHEET" in upper or "SCHEME" in upper):
            h = doc.add_heading(stripped, level=2)
            if h.runs:
                h.runs[0].font.color.rgb = RGBColor(0x05, 0x96, 0x69)
                h.runs[0].font.size = Pt(13)

        # Sub-headings (General Instructions, Part labels)
        elif stripped.lower().startswith("general instruction") or (len(stripped) < 60 and stripped.endswith(":")):
            h = doc.add_heading(stripped, level=3)
            if h.runs:
                h.runs[0].font.color.rgb = RGBColor(0x47, 0x55, 0x69)
                h.runs[0].font.size = Pt(11)

        # Regular lines
        else:
            para = doc.add_paragraph()
            para.paragraph_format.space_after = Pt(3)
            run = para.add_run(stripped)
            run.font.size = Pt(11)
            run.font.color.rgb = RGBColor(0x1E, 0x29, 0x3B)

    # ── Footer ────────────────────────────────────────────────────────────────
    doc.add_paragraph()
    footer = doc.add_paragraph("— Generated by Teacher Model App —")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if footer.runs:
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(0x94, 0xA3, 0xB8)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
